### PR TITLE
#66: Fix SimpleClosestPointProjection call in BvhContactManager

### LINKED ISSUE #66: fix SimpleClosestPointProjectionSingle call from BvhContactManager

### PR DESCRIPTION
**Pull request by nmm0**
FIxes #66

### CODE REVIEW

File: src/contact/parallel/bvh_contact_manager.cc [hunk 1]
```diff
@@ -16,16 +16,16 @@ namespace nimble {
...
-      for ( auto &&elb : _b.elements )
-        query_tree_local( tree, elb, [&_a, &_b, &elb, &res, this]( std::size_t _i ) {
+      for ( auto &&elb : _b.elements ) {
+        query_tree_local(tree, elb, [&_a, &_b, &elb, &res, this](std::size_t _i) {
           const auto &face = _a.elements[_i];
           const auto &node = elb;
           ContactManager::PROJECTION_TYPE proj_type;
           ContactEntity::vertex closest_point;
           double gap;
           double normal[3];
```
Comment (uhetmaniuk) [inline src/contact/parallel/bvh_contact_manager.cc:26]: Do you need to store the unit normal vector for computing the contact force?

Comment (rjones-sandia) [reply src/contact/parallel/bvh_contact_manager.cc:26]: Yes. The gap and normal are better/more convenient for commuting the contact force than just the projection point on the facet and the contacting node
