### PR TITLE
Fix main interface

### LINKED ISSUE #149: Preserve nimble::NimbleKokkosMain with shared pointers
To allow a general use of NimbleSM with user-defined materials, the refactor should preserve the interface with shared pointers: material_factory, contact_interface, block_material_interface_factory, and parser

These classes may need to rely on an (abstract?) base implementation.

### PR DESCRIPTION
**Pull request by uhetmaniuk**
Closes #149

### CODE REVIEW

**Comment by uhetmaniuk** [comment]
Description of changes:

- Creation of abstract base classes:
    - `class BlockBase` (``nimble_block_base.h``)  -- the derived classes are `nimble::Block` and `nimble_kokkos::Block`
        - In `nimble_kokkos::Block`, rename ``element_host`` and ``material_host`` as ``element_`` and ``material_`` to use the variables in the base class
    - `class BlockMaterialInterfaceBase` (``nimble_block_material_interface_base.h``)  -- the derived class is `nimble_kokkos::BlockMaterialInterface`
    - `class BlockMaterialInterfaceFactoryBase` (``nimble_block_material_interface_factory_base.h``)  -- the derived class is `nimble_kokkos::BlockMaterialInterfaceFactory`
    - `class MaterialFactoryBase` (``nimble_material_factory_base.h``)  -- the derived classes are `nimble::MaterialFactory` and `nimble_kokkos::MaterialFactory`

- Creation of files with one class: ``nimble_model_data_base.h``, ``nimble_model_data.h`` 
    - Rename the structure ``nimble_kokkos::FieldIds`` as ``nimble::FieldIds`` at the top level

- Update of ``nimble_mpi.{h,cc}`` and ``nimble_mpi_main.cc`` to preserve interface with external libraries
    - ``nimble_mpi.cc`` uses ``dynamic_pointer_cast`` as a temporary solution while refactoring.

- Update of ``nimble_kokkos.{h,cc}`` and ``nimble_kokkos_main.cc``
    - ``nimble_kokkos.cc`` uses ``dynamic_pointer_cast`` as a temporary solution while refactoring.

- ``nimble_tpetra_utils.{h,cc}``  Minor clean-ups

- ``CMakeLists.txt`` Insertion of new files

**Comment by japlews** [comment]
@uhetmaniuk changes are required in Extras to get the code to build with the new main routines and common base classes, but no deal breakers. Tests pass!

File: src/nimble_block_material_interface_base.h [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+            const int num_block_elems_, const int num_points_per_block_elem_)
+      :
+      block(block_),
+      material_device(material_d_),
+      id(block_id_),
+      num_elems(num_block_elems_),
+      num_points_per_elem(num_points_per_block_elem_) {
+  }
+
+  nimble::BlockBase *block = nullptr;
```
Comment (japlews) [inline src/nimble_block_material_interface_base.h:63]: Storing a pointer to `BlockBase` is the tricky part here, since there is still not a clean interface to `NGPLameData`, `dynamic_cast`s to `nimble_kokkos::Block` are required in Extras. This can be part of a future refactor if needed.

File: src/nimble_block_material_interface_factory_base.h [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+class BlockMaterialInterfaceFactoryBase {
+public:
+
+  BlockMaterialInterfaceFactoryBase() = default;
+  virtual ~BlockMaterialInterfaceFactoryBase() = default;
+
+  virtual std::shared_ptr<nimble::BlockMaterialInterfaceBase> create(double time_n, double time_np1,
+                                                         const nimble::FieldIds &field_ids,
+                                                         const std::vector<nimble::BlockData> &blocks,
+                                                         nimble::BaseModelData *model_data_ptr) const = 0;
```
Comment (japlews) [inline src/nimble_block_material_interface_factory_base.h]: `ModelDataBase` to be consistent?

**Review by japlews — APPROVED** [review]
Left a couple of minor comments but overall this works and is a step in the right direction!

File: src/nimble_block_material_interface_base.h (hunk 1 above)
Comment (uhetmaniuk) [reply src/nimble_block_material_interface_base.h:63]: @japlews
I noticed that `std::shared_ptr<nimble::NGPLAMEData> ngp_lame_data_` is a member of `nimble_kokkos::Block` as a _placeholder_ (?). 

What do you think if I put this member in the base class and add to the base class interface the routine `std::shared_ptr<nimble::NGPLAMEData> GetNGPLAMEData()` ? 

If that helps, I could do the similar modification for `nimble_kokkos::MaterialFactory` and `nimble::MaterialFactoryBase`

File: src/nimble_block_material_interface_factory_base.h (hunk 2 above)
Comment (uhetmaniuk) [reply src/nimble_block_material_interface_factory_base.h]: Will do.

File: src/nimble_block_material_interface_base.h (hunk 1 above)
Comment (japlews) [reply src/nimble_block_material_interface_base.h:63]: @uhetmaniuk I vote to leave it as is—more of just a reminder for me that this awkward relationship should be fixed. It needs to be moved out of NimbleSM anyway; it's the last holdover from inverting the dependency of NimbleSM -> Extras.

Comment (uhetmaniuk) [reply src/nimble_block_material_interface_base.h:63]: @japlews OK. Will keep it as discussed. Thank you.
